---
- hosts: all
  handlers:
    - name: "restart apache"
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    # - name: "create test file"
    #   shell: "echo 'writing something in the terminal' >> test.txt"
    - name: "update apt cache"
      become: yes
      apt:
        update_cache: yes
    
    - name: "apt upgrade"
      become: yes
      command: apt upgrade -y

    - name: "Install packages"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php7.4
        - apache2
        - libapache2-mod-php7.4
        - php-mysql
        - php-curl
        - mysql-server
        - python3-pycurl
        - python3-mysqldb
        - unzip

    - name: "downloading wordpress"
      get_url:
        url: "https://br.wordpress.org/latest-pt_BR.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: "unpacking the files"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www"
        remote_src: yes
      become: yes

    - name: "make a copy of the files"
      copy:
        src: "/var/www/wordpress/wp-config-sample.php"
        dest: "/var/www/wordpress/wp-config.php"
        remote_src: yes
      become: yes

    - name: "config wp-config with passwords"
      replace:
        path: "/var/www/wordpress/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'nome_do_banco_de_dados_aqui', value: 'db_wordpress' }
        - { regex: 'nome_de_usuario_aqui', value: 'root' }
        - { regex: 'senha_aqui', value: 'root' }
      become: yes

    - name: "changing directory rendering from apache to wordpress"
      copy:
        src: "apache/000-default.conf"
        dest: "/etc/apache2/sites-available/000-default.conf"
      become: yes
      notify:
        - "restart apache"

    - name: "up mysql"
      become: yes
      service:
        name: mysql
        state: started

    - name: "create password for user root mysql"
      become: yes
      mysql_user:
        name: root
        host: localhost
        password: root
        priv: "*.*:ALL,GRANT"

    - name: "create database mysql"
      mysql_db:
        name: db_wordpress
        login_user: root
        login_password: root
        state: present

    - name: "copying new theme"
      copy:
        src: "theme/blocksy.1.8.95.zip"
        dest: "/tmp/blocksy.1.8.95.zip"
      become: yes

    - name: "unpacking theme"
      unarchive:
        src: "/tmp/blocksy.1.8.95.zip"
        dest: "/var/www/wordpress/wp-content/themes"
        remote_src: yes
      become: yes
